### ISSUE TITLE
Twilight Forest Biomes Overwritten

### ISSUE THREAD

**Issue by Graywaren** [MrScautHD/Beyond-Earth#100]
Hi
I'm playing a 1.16.5 Seaopolis modpack and have discovered that BE biomes have overwritten areas in Twilight Forest. This happened after TF generated naturally. I went to TF first, then eventually went to a few planets, then went back to twilight forest and discovered that in a large section surrounding the original spawn portal in TF the biomes had been changed to a mishmash of the planet biomes. It didn't re-gen blocks, but the sky colors and particles are now matching the BE planet biomes. It also seems to have caused some issues with TF generating biomes correctly, or caused it to re-generate things improperly. I'm not entirely sure because it's very weird and I haven't encountered anything similar before. I adore TF and would really like to get this fixed so I can enjoy the biomes in their proper places. Do you have any idea why this is occurring or how to fix it? Here's a couple screen shots.

Here you can see the sky color and biome of Mars:
![2022-03-16_22 01 07](https://user-images.githubusercontent.com/46462871/159087791-113afe82-a6ff-4a19-8dda-7d7452758e1e.png)

Here's my map, there's an oval of pale yellow green almost centered on the player icon that is entirely made up of planet biomes and then in the bottom right you can see the spots where it caused a strange overwrite or something, but with twilight forest's own biomes.
![2022-03-18_17 54 23](https://user-images.githubusercontent.com/46462871/159090027-39a932d2-7037-4839-b421-eeccaefefcfb.png)

Here is the Twilight Forest Map that I generated before going to any planets. You can see all the biomes are consistent and natural:
![2022-03-18_17 57 27](https://user-images.githubusercontent.com/46462871/159090073-697641f9-7668-40ed-bcfd-9e2b9e64a375.png)

Thanks for any help!

**Comment by MrScautHD** [comment]
Sry, but idk we do the biomes like all other guy, maybe a other mod brake it Terrablender...
