### ISSUE TITLE
Tier 1&2 Rockets Stopped Launching

### ISSUE THREAD

**Issue by Graywaren** [MrScautHD/Beyond-Earth#101]
Hi
Playing a Seaopolis 1.16.5 modpack. My friend and I were able to launch with Tier 1 Rockets to get to the moon, however when we made the Tier 2 Rocket and tried to launch to Mars, the rocket did not lift off. It counted down, makes all the noise, but it just sits there. Eventually I just have to /kill the entity. We tried a Tier 3 Rocket and that launches just fine. I recently tried a Tier 1 Rocket again, and now it is doing the same as the Tier 2 Rocket and refusing to actually lift off until I just have to kill the entity. There's no errors in either my client or the server logs, so unfortunately I don't have any debug info that might be helpful. If there's any test you need me to perform, let me know.

**Comment by MrScautHD** [comment]
Can you show me a Video?

**Comment by MrScautHD** [comment]
Im sure it is a other mod, i close it now bit i can laiter reopen it
