### ISSUE TITLE
Game (and rocket) Crash With 3rd Person Camera View In Space

### ISSUE THREAD

**Issue by Graywaren** [MrScautHD/Beyond-Earth#102]
Playing 1.16.5 Seaopolis Modpack on  a private server. I've discovered that my game crashes if I attempt to descend to a planet in third person camera mode. I love the rocket launch animation and so had it in 3rd person view to watch the launch. However, when I chose the planet in the catalog my game would immediately crash. I'd log back on to find myself dead in a ditch (lol) on the planet I had chosen. I thought perhaps there was a conflict with a client side mod I had, because my friend did not have this issue. I pulled out my client mods and did some testing and was able to complete a landing just fine. I tried again and this time on the descent I hit F5 to change the view and the game immediately crashed again. I put all my client mods back in and tried again. Without being in 3rd person view I was indeed able to land safely. I've included the crash log for what shows up in my client log when it crashes with the third person view
[ThirdPersonViewBECrash.txt](https://github.com/MrScautHD/Beyond-Earth/files/8307963/ThirdPersonViewBECrash.txt)

**Comment by MrScautHD** [comment]
Sry but 1.16.5 is not anymore supported, and i reworked the renderer in 1.18.2 again, but i think it is ni problem by me
