### ISSUE TITLE
Sounds & Cheese

### ISSUE THREAD

**Issue by Graywaren** [MrScautHD/Beyond-Earth#103]
Seaopolis 1.16.5 Modpack on a private server. The sounds for block breaking and placing are muted, nearly inaudible compared to the volume of those sounds in overworld, however sounds like a chest opening are still at normal volume making it quite painful if you turn the volume up to hear the muted sounds. I'm uncertain if the sound dampening is intended, but if so I would suggest it effect all sounds and be an option to disable or to set the level in a config file. Also, the moon cheese ore does not seem to have any cheese drops. I would expect with it being called an ore that there would be a way to use it for something, but haven't discovered any uses yet. Not sure if this just isn't implemented, or if there was a bug, so I just wanted to mention it.
Thanks!

**Comment by MrScautHD** [comment]
We changeing just natural sounds, and we exrta made it muted so dont high up the volume 😁and the chesse is just a joke thing
