### ISSUE TITLE
Loading world version 6.0k into 6.1 datapack error

### ISSUE THREAD

**Issue by Trnrr** [MrScautHD/Beyond-Earth#106]
Minecraft 1.18.2
Beyond-Earth-1.18.2-6.1
Forge 40.0.52

Loading a world from mod version 6.0k in version 6.1 results in a a datapack error message and won't let you the world. Clicking "Safe Mode" does nothing.

![image](https://user-images.githubusercontent.com/20446954/163517104-f2a9f9ef-657f-4591-90f1-ace95a5a4c96.png)

You can recreate this with having only Beyond Earth installed.

1. Use forge 40.0.52
2. Add Beyond Earth 6.0k
3. Open game and create a new world
4. Quit game
5. Update to Beyond Earth 6.1
6. Open game and load previous world
7. Will error

Downgrading from version 6.1 to 6.0k lets me load the world. However, I'm not sure if that would cause any issues but my base looks fine so far.

**Comment by MrScautHD** [comment]
Delete the old Dimensions of Beyond earth

**Comment by Trnrr** [comment]
Is there another place where dimension data is stored? I deleted the beyond earth file from ../saves/Survival/dimensions but I still get the error when I try to load the world.

**Comment by MrScautHD** [comment]
mhh wierd

**Comment by Klouver-github** [comment]
I am also having same problem

**Comment by samiam567** [comment]
I am as well. The error said something about the registry data.
