### ISSUE TITLE
New update causes pre-launch crash.

### ISSUE THREAD

**Issue by ShibeTemple** [MrScautHD/Beyond-Earth#109]
There is no log output, simply a super-early crash with Beyond-Earth-1.18.2-6.1.jar. This was not an issue with the previous 6.0k version. Here is a latest.log. There is no crash report, the game simply closes back to launcher.

https://gist.github.com/ShibeTemple/0c6d664acb45a0de68e8d64ad5a8e7b2

**Comment by ShibeTemple** [comment]
Crash still occurs without optifine as well.

**Comment by MrScautHD** [comment]
update your forge version
