### ISSUE TITLE
multi-player requires each player to destroy lander

### ISSUE THREAD

**Issue by oM3fC** [MrScautHD/Beyond-Earth#110]
Running Beyond Earth 1.18.2-6.0k on Forge 1.18.2-40.0.52 in server mode with 2 players.

Multi-player does not recognize when a player removes the lander. The lander remains visible to all other server players and world behaves as if the lander still exists. Player 1 may not place the recovered rocket again until the lander is sneak-actioned by all other players.

Player 1/3 launches, lands, retrieves rocket, sneak-action's the lander.
Player 2/3 goes to the same location and sneak-action's the lander.
Player 3/3 goes to the same location and sneak-action's the lander.
Server recognizes lander as removed from launch/landing possition.
Player 1/3 may now reuse the launch pad.

When player 1 removes the lander, all player sessions should recognize the change. Maybe the last player to use hte rocket/lander must remove it; or any player may remove a lander and that lander is removed from all player's sessions. (rocket could drop to ground, be lost, or whatever it does now when a lander is destoryed with rocket in inventory still)

(screenshot; player 2 still able to see lander while player 1 destroys the launch pad under it
![2022-04-17_11 11 15](https://user-images.githubusercontent.com/17787690/163722338-420729d8-d0f0-466e-a207-9fea28296957.png)
)

**Comment by MrScautHD** [comment]
what?

**Comment by MrScautHD** [comment]
ah ok i understand, thx for you bug report, pls report more bugs if you found any!
