### ISSUE TITLE
Solar Generator block should recognize open and transparent blocks above as "sun light"

### ISSUE THREAD

**Issue by oM3fC** [MrScautHD/Beyond-Earth#111]
If a glass block or open Trap Door are placed above a Solar Generator block, the generator behaves as if the sunlight is blocked.

[sunlight]
[emtpy]
[generator; charging]

but

[sunlight]
[clear glass; block (1 block or column)]
[generator; not charging]

and

[sunlight]
[trap door; open]
[generator; not charging]

Could solar generator blocks recognize the sun as visible if blocks above are clear glass, or open Trap Doors? (Eg. sun channel opened/closed, or column of clear glass from surface to top of generator, or generator under a clear glass dome on moon.)

![2022-04-17_12 09 51](https://user-images.githubusercontent.com/17787690/163723115-86690f6d-57da-4c83-a5b1-c834221c09bb.png)
)

**Comment by MrScautHD** [comment]
that is not really possible but i try my best to fix it

**Comment by MrScautHD** [comment]
not fixable

**Comment by oM3fC** [comment]
Thank you for trying. Solar power under sealed domes or with covers that open/close by redstone ciruites would both be interesting.

If it helps, the minecraft Vampirism Mod recognize sunlight through other blocks. That may provide an example if you have not already looked at it. A vampire player character will take sun-damage through an open trap door while the power generator under remains "off". (curseforge project ID 233029, GNU Lesser license)

**Comment by MrScautHD** [comment]
Fixed
