### ISSUE TITLE
[BUG] Issue with rendering liquids

### ISSUE THREAD

**Issue by TheRealM18** [MrScautHD/Beyond-Earth#113]
So I know this sounds weird, but if you have REI installed, and Beyond Earth, the game will crash on launch.

This is not under a development build of Beyond Earth either.  mostly any other mod, that adds liquids are fine too.

Forge: 40.1.0
Beyond Earth 6.1
Roughly Enough Items: 8.1.449
REI Compatibility Workaround: 8.1.449

Reproduce, put those mods in the same modpack together, and will crash.

[crash-2022-04-21_14.28.33-client.txt](https://github.com/MrScautHD/Beyond-Earth/files/8533360/crash-2022-04-21_14.28.33-client.txt)

**Comment by MrScautHD** [comment]
i don't see a bug (we write in dc)
