### ISSUE TITLE
feature request; add an Earth-Time clock and/or craftable planetary clocks

### ISSUE THREAD

**Issue by oM3fC** [MrScautHD/Beyond-Earth#114]
This is purely a feature request/idea if easy to add or interesting. Could you add player craftable planetary clocks that display a specific planet day/night cycle.

In-game examples:
* Players who collect flags and globes, can also craft/collect clocks as they travel further
* Players who build ground stations can have a wall of clocks (in item frames?)
* Players travelling can see if it's day/night on earth when returning (or when landing on other planets that have "sunlight")
* In multi-player, Player 1 (on the ground) can see if it's day/night time for player 2 on another planet

Maybe there is a "Planetary Clock" crafting recipe and it displays the name/time of the planet it was crafted on? A player must travel to the moon before they can make a be_clock_moon to bring back to earth. (and can make a be_clock_earth and take it to the moon)

Maybe the player needs to craft a clock, then combine that with gold/redstone/ironplate and someting unique to the planet; a loadstone that sets the clocks time instead of setting a compass direction? Once the clock is made, that's the time it displays no matter what planet you take it to (except the Nether and where clocks don't work at all).

Background and a second option/solution:

The specific idea came from playing Beyond Earth and Vampirism Mod together. If the player is a vampire, they take sun-damage from daylight and become very aware of day/night in the game. If they launch/land at night, all is good. If they land during the day (moon to earth), there is no way to survive the landing (land to fast and crash, land to slow with sundamage). And there is no way to know if it will be daylight when you land back on earth. An Earth-Time clock or clocks set to planetary time/cycles would be a great addition.

A second option might be to mark the rocket/lander objects as "covered" or "not directly under sunlight" if there is a global attribute. I don't know if all mods read the rainy/sunny/night sunlight level from the same game function. If each mod tracks sunlight exposure indavidually then this does not work. But clocks, work everywhere if you can add them.

**Comment by MrScautHD** [comment]
Its a good idea i add it to my idea list! (i want to add it in future!)
