### ISSUE TITLE
Fabric 1.18.2

### ISSUE THREAD

**Issue by KevinKharma1** [MrScautHD/Beyond-Earth#118]
Is there a playable version for fabric 1.18.2?

**Comment by omrumbakitemiz** [comment]
https://github.com/MrScautHD/Beyond-Earth/tree/1.18-Fabric#beyond-earth-for-minecraft-118-fabric

There is a fabric branch and in README file it’s says mod is not playable on fabric right now, still missing some core items.

**Comment by AlexNijjar** [comment]
Expect at least another month for Fabric-playable versions. Most of the content has been added, but as the readme says, it is not ready for survival yet.
