### ISSUE TITLE
Beyond earth molten metals removed in 1.18.2

### ISSUE THREAD

**Issue by Warhand** [MrScautHD/Beyond-Earth#119]
In the latest 1.18.2 release of Beyond earth (6.1) molten metals have been removed, despite tinkers construct having already made it to this version.

I'm unsure if this is intended or unintented, but JAOPCA still detects there being tags for molten metals, and so doesn't automatically generate them, and Crafttweaker doesn't detect the fluids.

**Comment by MrScautHD** [comment]
Tinkers not anymore Supported
