### ISSUE TITLE
There are 1150 lines of errors during server startup

### ISSUE THREAD

**Issue by ghost** [MrScautHD/Beyond-Earth#120]
Parsing error loading recipe

can be seen in the server latest.log after startup

attaching text file:
[latest.txt](https://github.com/MrScautHD/Beyond-Earth/files/8713501/latest.txt)

Verions:
mc 1.18.2
forge 40.1.20
beyond earth 6.1
Tcon 3.5.0.17
Tcon-Mantle 1.9.20
Jaopca 4.1.5.5

**Comment by MrScautHD** [comment]
Fixed in 1.19
