### ISSUE TITLE
[1.18.2] Lander and ship are not spawning when going to the moon

### ISSUE THREAD

**Issue by ProsperCraft** [MrScautHD/Beyond-Earth#132]
### Mod loader

Forge

### Minecraft version

1.18.2

### Beyond Earth version

Beyond-Earth-1.18.2-6.2

### Modloader version

1.18.2-40.1.51

### The latest.log file

https://gist.githubusercontent.com/ProsperCraft/85c9818b43dbe50f873d04222874b5a4/raw/f1c5e87fde372dd4b15fd18063cfb20b6dd9395b/gistfile1.txt

### Issue description

If you don't sleep, then go launch in to space with a Tier 1 rocket phantoms come and break your rocket then you spawn at the moon at Y 500 with no rocket and fall to the planet and make a giant crater with no ship in sight.

Possible solutions might be to make the phantoms not spawn wherever you have the player in limbo while picking a destination.

### Steps to reproduce

1. don't sleep
2. take off in Tier 1 rocket
3. fiddle with the desination looking for the moon and take long enough the phantoms attack.
4. fall to planet and make a giant crater.  You live here now.

**Comment by ProsperCraft** [comment]
Update- player that came to rescue me spawned without a ship as well, no phantoms, was stuck up in atmo and couldn't get down until relog.

**Comment by ProsperCraft** [comment]
ok, another update, the space lander just is never spawning, we tried almost a dozen times.

**Comment by ProsperCraft** [comment]
https://github.com/jonafanho/Minecraft-Transit-Railway/issues/427

**Comment by Dzuco** [comment]
I have the same issue, any news?

**Comment by MrScautHD** [comment]
the solution is already here!

**Comment by Sebastrn** [comment]
Hello @MrScautHD 

You mention the solution ia already here but I don't see it.

Could you please help us?
