### ISSUE TITLE
Server latest.log file generates almost 500 lines of errors during startup

### ISSUE THREAD

**Issue by ghost** [MrScautHD/Beyond-Earth#133]
### Mod loader

Forge

### Minecraft version

1.18.2

### Beyond Earth version

6.2

### Modloader version

40.1.60

### The latest.log file

https://pastebin.com/0FSfPghm

### Issue description

I think it could be a conflict with the latest version of tinkers construct

### Steps to reproduce

1. Launch the server
2. Read the client latest.log file

**Comment by clarketronics** [comment]
I've got exactly the same issue, any idea on timeline for a fix?

**Comment by ghost** [comment]
> I've got exactly the same issue, any idea on timeline for a fix?

We need to wait for the developer(s) to provide an update. EDIT oops didn't realize you said timeline lol

**Comment by gisellevonbingen** [comment]
Applied at #142
