### ISSUE TITLE
Rockets are broken on 1.19

### ISSUE THREAD

**Issue by glowiak2** [MrScautHD/Beyond-Earth#136]
### Mod loader

Forge

### Minecraft version

1.19

### Beyond Earth version

6.3

### Modloader version

41.0.99

### The latest.log file

https://0x0.st/o1xX.txt

### Issue description

When trying to go to literally any planet or moon, it sents me to earth

### Steps to reproduce

Compile this mod, run it with latest forge, try to go to any planet

### Other information

Is there any command or something to take me to other planet without using rockets?

**Comment by MrScautHD** [comment]
try to create a new world

**Comment by MrScautHD** [comment]
and i saw never a log like this, pls use the normal log that one is disgusting

**Comment by MrScautHD** [comment]
i think its a mc issue so just create a new world or try other things

**Comment by glowiak2** [comment]
But this is a normal log. If not, then what do you mean by the term "normal log"?

**Comment by glowiak2** [comment]
Nvm created a new world and rocket successfully took me to Mars
