### ISSUE TITLE
Add Cardinal Components as a Dependency on Curseforge

### ISSUE THREAD

**Issue by Technomancer666** [MrScautHD/Beyond-Earth#138]
### Mod loader

Fabric

### Minecraft version

1.19

### Beyond Earth version

1.0.0

### Modloader version

Fabric 0.14.8

### The latest.log file

The game freezes indefinitely, it doesn't crash. 

### Issue description

Beyond Earth for Fabric will not run without Cardinal Components installed, therefore it should be listed as a required dependency on CuresForge.

### Steps to reproduce

Trying to run the mod without Cardinal Components, will result in the game freezing when loading the terrain of a new world.

**Comment by AlexNijjar** [comment]
Hey, please report Beyond Earth, Fabric bugs here:
https://github.com/AlexNijjar/Beyond-Earth-Fabric/issues

Beyond Earth, Fabric is not available for 1.19 yet. It also does not require Cardinal Components, which is not used anywhere in the code. Try creating a brand new 1.18.2 instance in your launcher with only Beyond Earth, Cloth Config and Fabric API. These are the only required mods.
