### ISSUE TITLE
Please make machines more configurable (FE/t, mb/t)

### ISSUE THREAD

**Issue by bmwalter68** [MrScautHD/Beyond-Earth#140]
### Describe the feature

For pack builders, balancing the interaction of various mods is important, especially when we want to use something like exploring space as a late-game perk.  It would be great for us to be able to specify not only cook time for items in BE machines, but how much FE/t the machine uses to help with pack balance.  This extends to the FE/t output of the Coal/Solar generators as well.

For that matter, being able to specify mb/t pumped would be useful as well.

**Comment by gisellevonbingen** [comment]
Applied at #145

**Comment by MrScautHD** [comment]
Added
