### ISSUE TITLE
Please make worldgen a configurable option

### ISSUE THREAD

**Issue by bmwalter68** [MrScautHD/Beyond-Earth#141]
### Describe the feature

When balancing ores/fluids in a large modpack authors often consolidate worldgen into a single mod like Oretweaker to have full control over how resources generate.  It would be very helpful to be able to disable planetary oregen and generation of oil in the overworld so that it can be handled by other means if the modpack authors desire it.

**Comment by MrScautHD** [comment]
you can do that already all

**Comment by bmwalter68** [comment]
Great!  Where exactly are the config options to disable worldgen for ores?

**Comment by MrScautHD** [comment]
its all handled with datapacks

**Comment by bmwalter68** [comment]
Would I be correct in assuming this would involve modifying the various ore_replacebles tags?

EDIT: I think I found it in dimensions/moon.json  Correct?
