### ISSUE TITLE
[Feature Request] Custom planet/system definition

### ISSUE THREAD

**Issue by mechobree** [MrScautHD/Beyond-Earth#165]
### Describe the feature

I think it would be very great for modpack makers if there was a config file where you could define custom planets (and systems) a-la AR's planet defs style.

There could be a option to set the planets icon (which could also be the picture for orbit) & and other various settings i.e; gravity, breathability, rocket tier along with dim mapping. It doesn't have to be able to define it's own custom dimensions, just mapping an already existing dimension would be awesome :)

**Comment by MrScautHD** [comment]
Added
