### ISSUE TITLE
Config file is incomplete 

### ISSUE THREAD

**Issue by AaroonHindle** [MrScautHD/Beyond-Earth#169]
### Mod loader

Forge

### Minecraft version

1.18.2

### Beyond Earth version

6.2

### Modloader version

forge 40.1.73

### The latest.log file

https://pastebin.com/seYkVFze

### Issue description

looking at the code on here it looks like there's things ready for a config but when i loaded the mod there was only the entities configuration but no other machines i looked on curseforge and i didnt see any newer versions

Existing config folder contains:

["Beyond Earth Config"]
	#Enable or Disable Alien to Spawn
	"Alien Spawn" = true
	#Enable or Disable Alien Zombie to Spawn
	"Alien Zombie Spawn" = true
	#Enable or Disable Star Crawler to Spawn
	"Star Crawler Spawn" = true
	#Enable or Disable Pygro to Spawn
	"Pygro Spawn" = true
	#Enable or Disable Pygro Brute to Spawn
	"Pygro Brute Spawn" = true
	#Enable or Disable Mogler to Spawn
	"Mogler Spawn" = true
	#Enable or Disable Martian Raptor to Spawn
	"Martian Raptor Spawn" = true
	#Enable or Disable Player Oxygen System
	"Player Oxygen System" = true
	#Enable or Disable Entity Oxygen System
	"Entity Oxygen System" = true
thats it

**Comment by MrScautHD** [comment]
all is working with datapacks

**Comment by MrScautHD** [comment]
if i understand anything wrong let me know and i reopen the issue

**Comment by AaroonHindle** [comment]
ah... where do you get the data packs from as i dont think i saw where to get them from. thanks for the reply :)
