### ISSUE TITLE
when adding mod server dosent start up

### ISSUE THREAD

**Issue by TGDCCow** [MrScautHD/Beyond-Earth#17]
I am able just to launch and play Minecraft with the mods but when I try to launch the cmd starts spamming the same code and then closes here is the crash report  
[crash-2021-12-19_00.19.21-server.txt](https://github.com/MrScautHD/Beyond-Earth/files/7740152/crash-2021-12-19_00.19.21-server.txt)

**Comment by MrScautHD** [comment]
Already fixed wait on 5.7
