### ISSUE TITLE
Disabling STEEL on the config

### ISSUE THREAD

**Issue by SheroxGG** [MrScautHD/Beyond-Earth#170]
### Describe the feature

I am adding this Amazing mod to a new ModPack I am creating, but the main problem is that this mod adds Steel which is a really common ore from many other mods. And the recipe is so cheap, basically placing iron on a blast furnace, this makes other mods steel processing useless, for example immerisve engineering which is much harder. So Id love to be able to disable the recipe of steel from config. I cannot install craftweaker sadly. Thanks beforehand!

**Comment by MrScautHD** [comment]
use override with a datapack the recipe.

**Comment by MrScautHD** [comment]
for more help join our Discord, https://discord.gg/Xb2nPmN

**Comment by gisellevonbingen** [comment]
Has you reason can't install CraftTweaker?
