### ISSUE TITLE
Fuel Tags/Fuel Customisation

### ISSUE THREAD

**Issue by Koku0** [MrScautHD/Beyond-Earth#177]
### Describe the feature

A compatibility option for rocket fuel would be fantastic. Something like a forge tag that we can apply to various fluids (like Thermal Foundation's Refined Fuel) so that we can use alternate fuels.

### Additional context

**Usecase:** This would be fantastic for modpacks, as you could greatly integrate Beyond Earth with other mods.

**Comment by MrScautHD** [comment]
that is already in

**Comment by MrScautHD** [comment]
`


    /** FLUIDS */
    public static final TagKey<Fluid> FLUID_VEHICLE_FUEL_TAG = TagKey.create(Registry.FLUID_REGISTRY, new ResourceLocation(BeyondEarth.MODID, "vehicle_fuel"));
    public static final TagKey<Fluid> FLUID_OIL_FLUID_TAG = TagKey.create(Registry.FLUID_REGISTRY, new ResourceLocation(BeyondEarth.MODID, "oil"));
`

**Comment by gisellevonbingen** [comment]
If you is modpack develper, Add 'beyond_earth:vehicle_fuel' tag to your want fluid
Or just install addon mod, It is already support.
See the Fuel Compatibility section in this url
https://www.curseforge.com/minecraft/mc-mods/space-bosstools-giselle-addon

**Comment by Koku0** [comment]
My apologies, sorry for this. Thanks for clarifying everything.
