### ISSUE TITLE
Mapping from Dimension <-> Orbit

### ISSUE THREAD

**Issue by Thutmose** [MrScautHD/Beyond-Earth#179]
### Describe the feature

Ideally for an addon, I would like to be able to look up the following:

Given a mob's location, is it in orbit or is it on a planet.
If the mob is in orbit/planet, what dimension corresponds to the planet/orbit.

### Additional context

I am setting up my standard space-mod compatibility module for [pokecube](https://github.com/Pokecube-Development/Compat), which consists of the following:

Players can ride their Mega Rayquaza to/from orbit.
Certain pokemobs will be able to spawn in space/moons/etc.

And this request will greatly assist with the ease of setup of the first part, which I have already done a [basic prototype](https://github.com/Pokecube-Development/Compat/blob/1.18/src/main/java/pokecube/mod_compat/beyond_earth/Impl.java#L36-L63) of, but by manually identifying the dimensions:

![image](https://user-images.githubusercontent.com/2363472/191299320-cb923369-c2de-4ee5-90c8-7e7678db5abb.png)

**Comment by MrScautHD** [comment]
Hey, i can see what i can do!

**Comment by MrScautHD** [comment]
Added
