### ISSUE TITLE
Venus has too many spawns from other mods.

### ISSUE THREAD

**Issue by TheWitherlord** [MrScautHD/Beyond-Earth#180]
### Mod loader

Forge

### Minecraft version

1.18.2

### Beyond Earth version

6.2

### Modloader version

40.1.74

### The latest.log file

https://gist.github.com/TheWitherlord/d1cef1663d6fe83d66283c969f2ae92c

### Issue description

I don't know if this is a problem that can be fixed, but currently, Venus has mobs (I assume because biome dictionary) from other mods spawning and dying creating a large number of items dropping on the ground. Mobs like Desert and Cave Creepers from Creeper Overhaul and Ars Nouveau mobs are spawning and dying. The whole planet is a mob farm lol

### Steps to reproduce

1. Download Beyond Earth, Creeper Overahul, and Ars Nouveau
2. Load the game and go to Venus
3. Watch everything burn and enjoy the free mob farm
4.

### Other information
![download](https://user-images.githubusercontent.com/15508917/191851932-9de707e1-67b3-4383-900b-3581aecec862.png)

**Comment by MrScautHD** [comment]
That is not a issue of Beyond-Earth (report that by the mod owners of the mobs)
