### ISSUE TITLE
Please update 1.18.2 version. 

### ISSUE THREAD

**Issue by tuturox91** [MrScautHD/Beyond-Earth#181]
### Describe the feature

Last on forge page, mod updated in 28 May its 3 month ago. Pease if you can, build and add to curseforge newer version. Thank you for making such a great mod!

**Comment by Mirroray41** [comment]
MrScaut is reworking the internal code and its almost finished wait a few days

**Comment by tuturox91** [comment]
Oo,  im on hype.

**Comment by MrScautHD** [comment]
1.18 get a last update but not with all 1.19 features

**Comment by tuturox91** [comment]
Current 1.18.2 version on curseforge don't have normal config file.  But i see on guithub, current config  have more settings. Like count of buckets for fill up rocket, or machine settings.

**Comment by tuturox91** [comment]
> 1.18 get a last update but not with all 1.19 features

Current 1.18.2 version on curseforge don't have normal config file. But i see on guithub, current config have more settings. Like count of buckets for fill up rocket, or machine settings.
