### ISSUE TITLE
Guide for datapack config

### ISSUE THREAD

**Issue by alessandriLuca** [MrScautHD/Beyond-Earth#182]
### Describe the feature

Hi, im looking for a guide to modify the config of this mod and I found out that everything can be handled with datapack. Is there a guide to follow to handle so?

Thanks

**Comment by alessandriLuca** [comment]
Ok, if I understand correctly, Extracting the jar file it is possible to find the json files. I can modify the json just copying them in the correct folder path but in my datapack. This should do the job right?

**Comment by MrScautHD** [comment]
you can just look here on github

**Comment by MrScautHD** [comment]
and for a guide look a YT tutorial https://www.youtube.com/watch?v=9i5z7Eo9u4w&ab_channel=halbzwilling
