### ISSUE TITLE
[1.19.2] Pickaxe no longer valid tool to mine stone

### ISSUE THREAD

**Issue by Baggytrousers27** [MrScautHD/Beyond-Earth#188]
### Mod loader

Forge

### Minecraft version

1.19.2

### Beyond Earth version

Beyond-Earth-1.19.2-6.3

### Modloader version

43.1.47

### The latest.log file

https://gist.github.com/Baggytrousers27/201bc6c5275422e8e30b5478fc3f66e9

### Issue description

With Beyond Earth installed all (earth) stone types cannot be mined with a pickaxe.

**Comment by Gbergz** [comment]
can confirm

**Comment by MrScautHD** [comment]
Thx for your bug report get fixed in the next Version!

**Comment by trogarus** [comment]
Same issue, same versions of forge and Beyond Earth, but something that goes along with this is when I try to enter JAVD (Just Another Void Dimension) it also crashes.

Crash Log
[crash-2022-11-03_23.44.39-client.txt](https://github.com/MrScautHD/Beyond-Earth/files/9934870/crash-2022-11-03_23.44.39-client.txt)

Latest Log
[latest.log](https://github.com/MrScautHD/Beyond-Earth/files/9934879/latest.log)

Debug Log
[debug.log](https://github.com/MrScautHD/Beyond-Earth/files/9934880/debug.log)

**Comment by MrScautHD** [comment]
Fixed
