### ISSUE TITLE
[1.19.2] Beyond Earth Server Crash with other Custom Entity Mods present.

### ISSUE THREAD

**Issue by AsuraTakun** [MrScautHD/Beyond-Earth#195]
### Mod loader

Forge

### Minecraft version

1.19.2

### Beyond Earth version

6.3

### Modloader version

Forge 43.1.47

### The latest.log file

https://gist.github.com/AsuraTakun/103445f6d8e2e93f784ebc26f9e2a754

### Issue description

When adding Beyond Earth 6.3 to server, server crashes on boot right before the auth with mojang/microsoft step. Scrolling back appears to have crashed due to various mods with custom mobs/entities. Removing these mods just causes it to complain about other mods with custom mobs/entities. This only happens after installing Beyond Earth and removing it lets the server boot normally again.

Mods that have triggered from this: Twilight Forest, Mekanism Additions, Roots Classic, Biome Makeover, Chococraft, Ars Nouveau (I stopped checking after it was obviously going to keep doing this).

### Steps to reproduce

Install server with aforementioned mods and dependencies.
Boot normally
Shutdown server
Add Beyond Earth
Notice the spiraling error reports.

### Other information

The client seemed to at least load to the main menu, but I didn't test it further since the server wasn't booting. So if I were to guess, it is specifically a server related issue and not specifically an incompatibility with specific mods.

**Comment by waddon1** [comment]
I've been having this issue too I can upload my log file if it will help solve the issue.

**Comment by MrScautHD** [comment]
Server crash is in genrel a issue is fixed!
