### ISSUE TITLE
Beyond Earth Rocket Launch Pad Major Issue

### ISSUE THREAD

**Issue by RDP8** [MrScautHD/Beyond-Earth#209]
### Mod loader

Forge

### Minecraft version

1.19.2

### Beyond Earth version

6.3

### Modloader version

43.1.58

### The latest.log file

N/A

### Issue description

The rocketship launch pad is a missing texture and is impossible to craft. 

### Steps to reproduce

Try to craft it, won't work; look at it in the creative menu, its invisible, and when trying to place it, its a missing texture.

**Comment by MrScautHD** [comment]
That get fixed already :)
