### ISSUE TITLE
Option to Disable Custom Sky?

### ISSUE THREAD

**Issue by Flexico** [MrScautHD/Beyond-Earth#223]
### Describe the feature

Some of my favorite resource packs add a custom skybox, but BE overrides it. I'd like to keep the planets that the mod adds, but have them render over the sky from my pack.

For example, DokuCraft has a great nighttime skybox: https://dokucraft.co.uk/resource-packs/light

Thanks for your time~!

**Comment by shal0l** [comment]
Bump. Skybox too breaks with my favorite shaders, without a way to disable from either side.

**Comment by Ren-Shangxu** [comment]
I got this question, too. Please fix this problem. Thank you!

**Comment by MrScautHD** [comment]
planed: https://github.com/MrScautHD/Beyond-Earth/issues/245
