### ISSUE TITLE
Huge chunk of errors with lots of lag

### ISSUE THREAD

**Issue by TheDoctor1977** [MrScautHD/Beyond-Earth#224]
### Mod loader

Forge

### Minecraft version

1.18.2

### Beyond Earth version

1.18.2-6.2

### Modloader version

40.1.92

### The latest.log file

https://mclo.gs/dVsusGQ (errors begin at line 1784)

### Issue description

The issue occurred while I was in creative flying around and another server member landed on the moon in T4 rocket, none of us did anything out of the ordinary.

### Steps to reproduce

1. Fly around in creative
2. Have someone else land on the moon in a T4 rocket
3. Server will lag severely

### Other information

Our modlist is (according to Curseforge's modlist.html file):
[Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
[Xaero's World Map (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map)
[ZeroCore 2 (by ZeroNoRyouki)](https://www.curseforge.com/minecraft/mc-mods/zerocore)
[Kotlin for Forge (by thedarkcolour)](https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge)
[Collective (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/collective)
[ViesCraft Machines (by Vies)](https://www.curseforge.com/minecraft/mc-mods/viescraft-airships)
[Thermal Foundation (by TeamCoFH)](https://www.curseforge.com/minecraft/mc-mods/thermal-foundation)
[Coins JE (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/coins-je)
[Applied Energistics 2 (by AlgorithmX2)](https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2)
[Create: Factory (by antopfr90)](https://www.curseforge.com/minecraft/mc-mods/create-factory)
[Titanium (by Buuz135)](https://www.curseforge.com/minecraft/mc-mods/titanium)
[Macaw's Bridges (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-bridges)
[Fakename (by Tschipp)](https://www.curseforge.com/minecraft/mc-mods/fakename)
[Blocky Stone Doors (by Lothrazar)](https://www.curseforge.com/minecraft/mc-mods/blocky-doors)
[Ecologics (by SameDifferent)](https://www.curseforge.com/minecraft/mc-mods/ecologics)
[Create Deco (by talrey)](https://www.curseforge.com/minecraft/mc-mods/create-deco)
[AlchemyLib (by Dark_Arcana)](https://www.curseforge.com/minecraft/mc-mods/alchemylib)
[Architect's Palette (by Jsburg)](https://www.curseforge.com/minecraft/mc-mods/architects-palette)
[Boatload (by TeamAbnormals)](https://www.curseforge.com/minecraft/mc-mods/boatload)
[Caelus API (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/caelus)
[Create: Broken Bad (by jetpacker06)](https://www.curseforge.com/minecraft/mc-mods/create-broken-bad)
[Fast Leaf Decay (by olafskiii)](https://www.curseforge.com/minecraft/mc-mods/fast-leaf-decay)
[Extreme Reactors (by ZeroNoRyouki)](https://www.curseforge.com/minecraft/mc-mods/extreme-reactors)
[AppleSkin (by squeek502)](https://www.curseforge.com/minecraft/mc-mods/appleskin)
[Create (by simibubi)](https://www.curseforge.com/minecraft/mc-mods/create)
[Simple Voice Chat (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/simple-voice-chat)
[Security Craft (by Geforce132)](https://www.curseforge.com/minecraft/mc-mods/security-craft)
[Create : Misc & Things (by to0pa_fr)](https://www.curseforge.com/minecraft/mc-mods/create-misc-and-things)
[Ender Crop (by DrManganese)](https://www.curseforge.com/minecraft/mc-mods/ender-crop)
[Create Confectionery (by Furti_Two)](https://www.curseforge.com/minecraft/mc-mods/create-confectionery)
[Upgraded Netherite (by Rolfmao25)](https://www.curseforge.com/minecraft/mc-mods/upgraded-netherite)
[Blueprint (by TeamAbnormals)](https://www.curseforge.com/minecraft/mc-mods/blueprint)
[bad packets (by badasintended)](https://www.curseforge.com/minecraft/mc-mods/badpackets)
[Just Player Heads (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/just-player-heads)
[Ender Mail (by Chaosyr)](https://www.curseforge.com/minecraft/mc-mods/ender-mail)
[CoFH Core (by TeamCoFH)](https://www.curseforge.com/minecraft/mc-mods/cofh-core)
[Thermal Innovation (by TeamCoFH)](https://www.curseforge.com/minecraft/mc-mods/thermal-innovation)
[Beyond Earth (by mrscauthd)](https://www.curseforge.com/minecraft/mc-mods/beyond-earth)
[Flywheel (by jozufozu)](https://www.curseforge.com/minecraft/mc-mods/flywheel)
[Too Fast (by Noobanidus)](https://www.curseforge.com/minecraft/mc-mods/too-fast)
[Upgraded Netherite : Items (by Rolfmao25)](https://www.curseforge.com/minecraft/mc-mods/upgraded-netherite-items)
[GeckoLib (by ThanosGecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[Curios API (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/curios)
[ShetiPhianCore (by ShetiPhian)](https://www.curseforge.com/minecraft/mc-mods/shetiphiancore)
[Xaero's Minimap (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap)
[Savage & Ravage (by TeamAbnormals)](https://www.curseforge.com/minecraft/mc-mods/savage-and-ravage)
[Waystones (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/waystones)
[Create Stuff & Additions (by Furti_Two)](https://www.curseforge.com/minecraft/mc-mods/create-stuff-additions)
[Balm (Forge Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/balm)
[Additional Guns (by AutovwDev)](https://www.curseforge.com/minecraft/mc-mods/additional-guns)
[ConnectedTexturesMod (by tterrag1098)](https://www.curseforge.com/minecraft/mc-mods/ctm)
[Patchouli (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/patchouli)
[WTHIT Forge Edition (by badasintended)](https://www.curseforge.com/minecraft/mc-mods/wthit-forge)
[MrCrayfish's Gun Mod (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/mrcrayfishs-gun-mod)
[EnderTanks (by ShetiPhian)](https://www.curseforge.com/minecraft/mc-mods/endertanks)
[Elytra Slot (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/elytra-slot)
[Quirky Generators (by Dark_Arcana)](https://www.curseforge.com/minecraft/mc-mods/quirky-generators)
[SecretRoomsMod (by AbrarSyed)](https://www.curseforge.com/minecraft/mc-mods/secretroomsmod)
[Vanishmod (by MasterPerki)](https://www.curseforge.com/minecraft/mc-mods/vanishmod)
[Bookshelf (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/bookshelf)
[ESSENTIAL Mod (by SparkUniverse_)](https://www.curseforge.com/minecraft/mc-mods/essential-mod)
[Storage Drawers (by Texelsaur)](https://www.curseforge.com/minecraft/mc-mods/storage-drawers)
[CC: Tweaked (by SquidDev)](https://www.curseforge.com/minecraft/mc-mods/cc-tweaked)
[Farmer's Delight (by vectorwing)](https://www.curseforge.com/minecraft/mc-mods/farmers-delight)
[Upgraded Core (by Rolfmao25)](https://www.curseforge.com/minecraft/mc-mods/upgraded-core)
[EnderChests (by ShetiPhian)](https://www.curseforge.com/minecraft/mc-mods/enderchests)
[Framework (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/framework)
[Thermal Expansion (by TeamCoFH)](https://www.curseforge.com/minecraft/mc-mods/thermal-expansion)
[Upgraded Netherite : Ultimerite (by Rolfmao25)](https://www.curseforge.com/minecraft/mc-mods/upgraded-netherite-ultimerite)

**Comment by MrScautHD** [comment]
That is not the offical forge!

https://github.com/MrScautHD/Beyond-Earth/issues/245
