### ISSUE TITLE
Unnecessary string creation in isSpaceWorld() causing excessive TPS increase

### ISSUE THREAD

**Issue by LegendaryTot** [MrScautHD/Beyond-Earth#23]
I'm building a 1.18.1 pack and have been doing some profiling and noticed that this mod is accounting for a good portion of the TPS. Using spark profiler (https://spark.lucko.me/DJ3mxQgdBB) it looks like there's some unnecessary overhead in the isSpaceWorld() function in these lines here which is caused by creating bunch of strings. Each time you create a new ResourceLocation java has to do some work to create the string for the location.

https://github.com/MrScautHD/Beyond-Earth/blob/381ab568218ca429d65f9fa967d79c3eddeda3fc/src/main/java/net/mrscauthd/beyond_earth/events/Methodes.java#L146-L174

I think creating some public static variables and referencing them (similar to what you've done here) would be better: https://github.com/MrScautHD/Beyond-Earth/blob/cf6060e61c7a00f6338425810dd5e3d54c2c235c/src/main/java/net/mrscauthd/beyond_earth/gauge/GaugeTextHelper.java#L16

I see other spots in your code doing same thing that should also be using this pattern I think.

**Comment by MrScautHD** [comment]
Of course I take a look on it

**Comment by MrScautHD** [comment]
fixed https://github.com/MrScautHD/Beyond-Earth/commit/f9572dd951884af49152730945cd7f8f4f5e61c5 and https://github.com/MrScautHD/Beyond-Earth/commit/b937b5b75020012664e8cfe80d4a11848f4867c6
