### ISSUE TITLE
Sky rendering issue

### ISSUE THREAD

**Issue by CCr4ft3r** [MrScautHD/Beyond-Earth#234]
### Mod loader

Forge

### Minecraft version

1.19.2

### Beyond Earth version

6.4b

### Modloader version

43.2.3

### The latest.log file

not log related

### Issue description

After joining a created world I'm facing a sky rendering issue.

Probably an incompatiblity with Complementary Shaders and BSL shaders - the rendering issue does not happen when other Shaders like Sildur or Complementary Reimagined are choosed.

Minimum reproduction setting:
Oculus: 1.2.8a
Rubidium: 0.6.2
Complementary Shaders: 4.7 or BSL 8.2

without Beyond Earth
![without beyond earth](https://user-images.githubusercontent.com/118105353/224758142-3caa3dc6-7c3a-4107-8b4c-aed983197406.jpg)

with Beyond Earth
![with beyond earth ](https://user-images.githubusercontent.com/118105353/224758159-91eb9cbf-af88-4362-9c7b-d041ed1bb8d3.jpg)

### Steps to reproduce

1. Joining a created world

### Other information

also applies to other 1.19.2 versions

**Comment by MrScautHD** [comment]
Dupe: https://github.com/MrScautHD/Beyond-Earth/issues/245
