### ISSUE TITLE
Chests in structures have no loot. 

### ISSUE THREAD

**Issue by AbandonedPlayer** [MrScautHD/Beyond-Earth#239]
### Mod loader

Forge

### Minecraft version

1.19.2

### Beyond Earth version

6.4d

### Modloader version

Forge 43.2.8

### The latest.log file

https://gist.github.com/AbandonedPlayer/19199b9b6a8a9054c2e557eca6b22c01

### Issue description

Whenever visiting a structure ie: pygro tower, pygro village alien village, venus bullet **ALL** the chests are empty. I've watched youtube videos of people opening these chests and there is at least a few items in them each time. Is there a bug in the version I'm in? I've searched multiple structures and nothing each time.

**Comment by MrScautHD** [comment]
thx for your bug report, we want to take a look on it!

**Comment by AbandonedPlayer** [comment]
Thank you for your concern. Let me know if I can do anything to help. I will provide worlds or logs if it helps at all.

**Comment by Urielable** [comment]
I have the same issue,  have any update about this issue?

**Comment by AbandonedPlayer** [comment]
I've had no updates on this issue.

> I have the same issue, have any update about this issue?
