### ISSUE TITLE
Nothing is added

### ISSUE THREAD

**Issue by htmlcoder1562** [MrScautHD/Beyond-Earth#247]
### Mod loader

Forge

### Minecraft version

1.19.4

### Beyond Earth version

1.19.4

### Modloader version

Forge: unknown

### The latest.log file

https://www.curseforge.com/minecraft/mc-mods/beyond-earth/files    2nd from top

### Issue description

I don't see any difference between having it and not having it.

**Comment by st0x0ef** [comment]
Can I have the latest.log file pls

**Comment by MrScautHD** [comment]
There is no log.
