### ISSUE TITLE
recent source code

### ISSUE THREAD

**Issue by robberer** [MrScautHD/Beyond-Earth#249]
### Describe the feature

I would like to change some things in ore generation because e.g. moon desh spawns way to less in my opinion. it's harder to find then ancient debris :-) 

But it seems that this repository isn't up2date.

Last commit is from May 7 and last release in this repository is 6.1 but i use the recent version 6.4e.

Is the current source tree of this project not available in public domain anymore ?

regards
Robert

**Comment by st0x0ef** [comment]
The updated code is in my repository, I just put it here when I do a lot of change. If you want to see the code, check in my repository. I think that the quantity of ore is good but feel free to propose some new values and I'll check that.

**Comment by MrScautHD** [comment]
You can change them by your self with a datapack. (by updating it in BE check @st0x0ef)
