### ISSUE TITLE
Planet Menu Does Not Render, Instead Game Crashes

### ISSUE THREAD

**Issue by Cuttleguy** [MrScautHD/Beyond-Earth#255]
### Mod loader

Forge

### Minecraft version

1.18.2

### Beyond Earth version

6.2

### Modloader version

Forge 40.2.10

### The latest.log file

https://gist.github.com/Cuttleguy/56350c4057d28d33c6f4da43bbee1033

### Issue description

I am trying to create a modpack, and I needed an outer-space mod for 1.18.2. Ad Astra skipped the version, and Advanced Rocketry, as well as Galacticraft, had stopped at least 4 versions earlier. You were the best(only) option. This crash is extremely annoying. I am guessing it is an incompatibiliy, because when I tried to run the mod in an isolated enviorment, with the same forge version, it went just fine. In reading the changelogs, aparently there was a Planet Menu crash, fixed in 1.18.1. 

### Steps to reproduce

1. Make sure that all the mods are the same(I don't have any KubeJS scripts that I think could be a problem here)
2. Build your launch platform
3. Place any tier of Rocket on the platform
4. Fuel the Rocket
5. Enter the Rocket
6. Press Space
7. Once you reach the point where the Planet Menu GUI should display, the game will freeze and crash.
8. Reopen Minecraft.
9. Join World
10. Instant Crash, Same Report.

### Other information

Crash Report: https://gist.github.com/Cuttleguy/b2523c24cba6d7e746603438636ea925
Mod List: https://gist.github.com/Cuttleguy/e30cde361270858c93c18442149c89e4
OS: Windows 11
Launcher: Modrinth

**Comment by st0x0ef** [comment]
Do you have tried without the optimisation mods?

**Comment by Cuttleguy** [comment]
Not yet, but if that is the problem, how can I create compatibility between Beyond Earth and the optimization mods?
Also, Cosmos Addons is a custom made mod, just if you were wondering if that was the problem.

**Comment by Cuttleguy** [comment]
I disabled Connectedness, Radon, Reforgium, Radium, Rubidium, Rubidium Dynamic Lights, Rubidium Extras, Oculus, Oculus Flywheel Compat, Pluto, and Connected Textures Mod. Nothing changed, but the crash report was slightly different: https://gist.github.com/Cuttleguy/9f4a9bc23754df84b9432fc692f12a79.

**Comment by st0x0ef** [comment]
I think it's with oculus

**Comment by st0x0ef** [comment]
Try removing it completely

**Comment by Cuttleguy** [comment]
Just tried, still didn't work. Different crash: https://gist.github.com/Cuttleguy/d1ad68549dd52303998d6b3d4d7d8fca. Question, what led you to think it was Oculus?

**Comment by st0x0ef** [comment]
Sorry, I was thinking that oculus is a VR mod 😅 

I can't really help you since a new 1.18.2 version with all features of the 1.19 will be pushed soon.

**Comment by Cuttleguy** [comment]
It's fine if you can't fix it

**Comment by Cuttleguy** [comment]
I was just wondering what 6.0d meant because it mentioned a Planet GUI crash. Could that have something to do with my problem?

**Comment by MrScautHD** [comment]
For me looks like your forge version is to new, pls try the mod without any other mods.

**Comment by Cuttleguy** [comment]
I did, and it worked perfectly. Same forge version.

**Comment by MrScautHD** [comment]
> I did, and it worked perfectly. Same forge version.

Looks like one mod is not compatible with be (mixin)

**Comment by Cuttleguy** [comment]
Do you know which one?

**Comment by MrScautHD** [comment]
I think dynamiclights but im not sure. (just try to remove mods and see if it works.)
