### ISSUE TITLE
NPE from Event.SpaceSounds

### ISSUE THREAD

**Issue by jeremiahwinsley** [MrScautHD/Beyond-Earth#30]
Crash report:
https://gist.github.com/jeremiahwinsley/bd6e09709fe2876c6cfc33b1cd8eb992

This is likely triggered by some other mod attempting to play a sound, but crashes because `event.getSound()` is used here without checking for null first.

https://github.com/MrScautHD/Beyond-Earth/blob/c5a9c3565a14bb856b9a504de57ba108bfd8209a/src/main/java/net/mrscauthd/beyond_earth/events/Events.java#L303

**Comment by itsdinkd** [comment]
Been fixed a week ago, dev will not release fix until they are finished with their latest version. Makes no sense why no hot fix was released.

**Comment by MrScautHD** [comment]
thx for reporting this bug! https://github.com/MrScautHD/Beyond-Earth/commit/6b54279b0b694d7da8fb760ebd26bc3cf8686e26
