### ISSUE TITLE
Suggestion: A replacement for producing Steel needed.

### ISSUE THREAD

**Issue by Thunder-Nova** [MrScautHD/Beyond-Earth#39]
This is mostly based of of experience from since I played early modpacks. And having iron turn into another metal by simply smelting is a bad idea. Buildcraft and it's successor industrialcraft **used to** make Refined Iron in the same way, and it caused issues with other mods that did the same for steel. Causing a certain level of headaches for modpacks makers.

Perhaps making a Blast Furnace or/and Alloy smelter, or grind iron and coal together (making it unique to the mod if grinding multiple type of stuff together) to make a steel compound dust. ...Universal Grinder has a nice ring to it.

**Comment by MrScautHD** [comment]
just remove the recpie of the steel

**Comment by Thunder-Nova** [comment]
That was anticlimactic.

Would it be possible to make it so if it detects steel from other mods to disable itself? (just yes or no will suffice for this one.)
