### ISSUE TITLE
server side issue with rocket

### ISSUE THREAD

**Issue by DamianBerek** [MrScautHD/Beyond-Earth#40]
in server
launch rocket 
rocket despawns before reaching orbit player fell down every time.
works if i enable creative or in single player game but not on server

**Comment by MrScautHD** [comment]
pls show me a video or something that i can reprocedure that

**Comment by DamianBerek** [comment]
if you have another quality modpack 3 you can join my server and try for yourself i have no possibility to make video sadly

**Comment by MrScautHD** [comment]
> if you have another quality modpack 3 you can join my server and try for yourself i have no possibility to make video sadly

logs, forge version pls

**Comment by MrSheen123** [comment]
Here is a video of what happens, I will get you my logs now:

https://youtu.be/tIVOT0A9BSA

**Comment by MrScautHD** [comment]
Sry but that is not a BE issue, any other mods does brake it

**Comment by DamianBerek** [comment]
if other mod would break it then there would be info in client logs but there is nothing. i did multiple tests and always happen as on above video unless you turn on creative mode then it is fine so it got to be config issue for mod

**Comment by MrScautHD** [comment]
just search the mod that brake this my mod does it not

**Comment by MrSheen123** [comment]
There are no server logs to state any exceptions or anything happening and client side does not state anything either. I am happy to upload logs if needs be of both sides to show nothing is coming up.

**Comment by MrScautHD** [comment]
i don't need the logs anymore, just search the mod that do that

**Comment by DamianBerek** [comment]
what mod breaks it tell us as we dont have any errors in logs lol

**Comment by MrScautHD** [comment]
idk search it

**Comment by MrSheen123** [comment]
Does the mod have any known incompatibilities? I might be able to start a search for what is supposed to be breaking it

**Comment by DamianBerek** [comment]
lol duh but how if there is nothing in logs ? you expect people go through 300+ mods one by one searching for who knows what when nothing is in logs ?

**Comment by MrScautHD** [comment]
it is normal that nothing in the logs because this mod that delete this is not a bug it is like a feature to save fps i think

**Comment by DamianBerek** [comment]
only tthing i can think of is that  height limit for calling event when you leaving planet is greater than world height limit

**Comment by itsdinkd** [comment]
> it is normal that nothing in the logs because this mod that delete this is not a bug it is like a feature to save fps i think

It's possible forge is removing it because it's a ticking tile entity ready to crash the game. RemoveTickingTileEntities is set to true in forge-server.json so if this is the reason, then it is your mod, as it's ticking too much.

**Comment by MrSheen123** [comment]
I have added the line in forge-server.toml and will test it when I get a spare 5 minutes.

**Comment by MrScautHD** [comment]
> > it is normal that nothing in the logs because this mod that delete this is not a bug it is like a feature to save fps i think
> 
> It's possible forge is removing it because it's a ticking tile entity ready to crash the game. RemoveTickingTileEntities is set to true in forge-server.json so if this is the reason, then it is your mod, as it's ticking too much.

1. it is not a tile entity
2. i can not reproduce that

**Comment by MrSheen123** [comment]
As per my investigations on https://github.com/itsdinkd/AQM3/issues/26#issuecomment-1018887792 I have figured out the server is kicking people from rockets because they are moving too quickly. Building a rocket platform at near build limit for the world allows you to get into the world selection screen before the server kicks in with "player moved too fast"

**Comment by itsdinkd** [comment]
I actually meant to write Block entity. Forge has RemoveTickingBlockEntity in its server config. 

As for your investigation, I highly doubt that is the cause. That is a vanilla feature, but entities do not get removed otherwise players would have their boats removed when they are going too fast (which happens when anyone is on a boat)

**Comment by itsdinkd** [comment]
If it is indeed the case though by servers removing it due to that, forcing a player to build near build limits (not sure what this even means) is not really efficient, and most of the players of your mod on servers will not know to do this.

**Comment by DamianBerek** [comment]
yeah like i said before ( apparently didnt send message ) you get the same console message when in boat so it isnt the cause of rocket despawn. and building platform near height limit... well weird idea :D and takes whole point of using rockets at all if you can just build tower up to height limit and then place rocket to move one block and get to screen with selecting orbit

**Comment by MrScautHD** [comment]
Forge (Minecraft) dont remove entities if they move to quickly, a mod do that so search the mod and remove it

**Comment by MrSheen123** [comment]
The rocket doesn't despawn, you get kicked out of the rocket as the rocket continues upwards and the moving too fast is the only thing that showed up on the console at the exact time you get kicked out of the rocket

We are building a rocket pad at 320 height in the world just so we can play the mod as that is the only way I have gotten it to work without putting people in creative. I will try the removetickingblockentity when I get a spare couple minutes.

**Comment by MrSheen123** [comment]
I added your suggestion of RemoveTickingBlockEntity into forge-server.toml and it still did the same thing. Kick me out of the rocket while the rocket continued on, server saying I am moving too quickly and I am left to fall to my death.

So for giggles I put myself into creative and got to the world selection just fine as the server didn't kick me off the rocket for moving too quickly.

Yes, moving too quickly is meant to move you back to the last safe location but it does not move the rocket with me. I assume the rocket is classed as a vehicle like how boats are?

I performed these tests while on the ground and even recorded the game and my own panel to prove exactly what is happening: https://youtu.be/i6PgNxzjKFM

**Comment by DamianBerek** [comment]
i read something about MTQ fix ( moved to quick ) but cant find any file to edit threshold maybe that is the cause that rocket moves really much faster than boat
 tho from other side it always kick player at the same height so that would make it invalid point

**Comment by MrSheen123** [comment]
Yeah, normally with paper / purpur etc you can modify spigot.yml for upping these values but since forge does not have this capability it has been mods in the past but I can't find one on this version

**Comment by MrSheen123** [comment]
Yeah haha, I understand MTQ can be a pain but it is there for a reason

**Comment by MrScautHD** [comment]
If you get kicked enable fly on your server

**Comment by MrScautHD** [comment]
> > Forge (Minecraft) dont remove entities if they move to quickly, a mod do that so search the mod and remove it
> 
> None of the mods on my modpack does that. You aren't listening lmfao. If that was the case BOATS would be removed as they always show MTQ warning. The issue is with your rocket, not sure why you are so cocky to say it's not your fault. It's okay though I'm going to save everyone the trouble from those who reported from my modpack and just remove Beyond Earth. It's bad enough you took 3 weeks to fix a simple bug because you wanted to release the bug fix on a major release, and now you want to blame forge, and other mods for your ticking time bomb issue.
> 
> Good luck

1. What can i do if i dont have the time 
2. I can not release a half update
3. Its better if you remove the mod, i dont want that you can use it

**Comment by MrScautHD** [comment]
> > > Forge (Minecraft) dont remove entities if they move to quickly, a mod do that so search the mod and remove it
> > 
> > 
> > None of the mods on my modpack does that. You aren't listening lmfao. If that was the case BOATS would be removed as they always show MTQ warning. The issue is with your rocket, not sure why you are so cocky to say it's not your fault. It's okay though I'm going to save everyone the trouble from those who reported from my modpack and just remove Beyond Earth. It's bad enough you took 3 weeks to fix a simple bug because you wanted to release the bug fix on a major release, and now you want to blame forge, and other mods for your ticking time bomb issue.
> > Good luck
> 
> 1. What can i do if i dont have the time
> 2. I can not release a half update
> 3. Its better if you remove the mod, i dont want that you can use it

4. Its still not a bug the mod me
5. If you to dumb to setting up the anticheat right should you maybe not make a modpack

**Comment by MrScautHD** [comment]
> > Yeah haha, I understand MTQ can be a pain but it is there for a reason
> 
> Sad part is he either wants his players to build at world height or to fix minecraft instead of him fixing the speed of his rocket to not trigger the anti cheat. Some developers nowadays 🤣



> > Yeah haha, I understand MTQ can be a pain but it is there for a reason
> 
> Sad part is he either wants his players to build at world height or to fix minecraft instead of him fixing the speed of his rocket to not trigger the anti cheat. Some developers nowadays 🤣

That is not a bug by me again 🤦‍♂️

**Comment by SomeoneIs404** [comment]
> > Yeah haha, I understand MTQ can be a pain but it is there for a reason
> 
> Sad part is he either wants his players to build at world height or to fix minecraft instead of him fixing the speed of his rocket to not trigger the anti cheat. Some developers nowadays 🤣

Then fix it urself :) or shut up and listen to wat scaut's saying : the problem is caused by another mod and not his mod .

**Comment by DamianBerek** [comment]
looking at last few comments here i wonder how old are you guys lol such unprofessional discussion...

**Comment by DamianBerek** [comment]
> If you get kicked enable fly on your server

i have flight enabled on server.  i doubt it is because rocket fly too fast as i mentioned before it always happen at the same height. so my guess is that it have something to do with world height.

**Comment by nocturnalfoxboi** [comment]
excuse me sir, could you please keep beyond earth? i am sure that it is not too hard to say something like "remember to place your launchpad at least 200 blocks up to prevent some minor bugs". the beyond earth mod is a resurrection of my favorite mod and i have always been quite tied to space. please leave it in, i am sure if they know to make their pad a little higher they will not add anymore complaints

**Comment by SomeoneIs404** [comment]
> looking at last few comments here i wonder how old are you guys lol such unprofessional discussion...
We're running a server and we didnt get that problem . The mod developer , @MrScautHD , tried to explain several times it isnt a problem caused by his mod and rather something else ( not necessarily minecraft ) . And your friends/alts -or watever they 're- were the ones that made this discussion looks like kids fight , while scaut was calm in all his replys and provided explination for what he says ( he is german , he uses google translate to talk english ) . Although we dont have any problem with you bc unlike the other kids , you kept replying calmly . And about the bug , if more reports comes about same bug we will of course consider looking at what caused it ( even tho scaut alrdy said it isnt made by the mod , but the mod is rather affected by that bug ) .

Hope you understand , have a nice day sire

**Comment by YoureNotSmarthuh** [comment]
> > > > Forge (Minecraft) dont remove entities if they move to quickly, a mod do that so search the mod and remove it
> > > 
> > > 
> > > None of the mods on my modpack does that. You aren't listening lmfao. If that was the case BOATS would be removed as they always show MTQ warning. The issue is with your rocket, not sure why you are so cocky to say it's not your fault. It's okay though I'm going to save everyone the trouble from those who reported from my modpack and just remove Beyond Earth. It's bad enough you took 3 weeks to fix a simple bug because you wanted to release the bug fix on a major release, and now you want to blame forge, and other mods for your ticking time bomb issue.
> > > Good luck
> 
> 1. What can i do if i dont have the time
> 2. I can not release a half update
> 3. Its better if you remove the mod, i dont want that you can use it
> 4. Its still not a bug of my mod
> 5. If you to dumb to setting up the anticheat right should you maybe not make a modpack

"Enable flight" "you to dumb to set up anti cheat" 
![image](https://user-images.githubusercontent.com/90159319/150649066-7a242415-998d-4ce1-9cb6-63fde30ce170.png)
It's always been enabled even for new server owners who download the server pack, oh holy amateur. 

![image](https://user-images.githubusercontent.com/90159319/150649112-5d7a1bf8-cc57-4f2c-8418-991378826824.png)
This makes so much sense, but crazy how cocky this little kid is. Your code is trash, end of story.

**Comment by YoureNotSmarthuh** [comment]
> > > Yeah haha, I understand MTQ can be a pain but it is there for a reason
> > 
> > 
> > Sad part is he either wants his players to build at world height or to fix minecraft instead of him fixing the speed of his rocket to not trigger the anti cheat. Some developers nowadays 🤣
> 
> Then fix it urself :) or shut up and listen to wat scaut's saying : the problem is caused by another mod and not his mod .

Listen to what he is failing to translate and blame his entire problem on "enable-flight" which is already on? lmfao. If you have nothing to contribute why are you here? to white knight?

**Comment by MrScautHD** [comment]
thx for the nice words :)

**Comment by bingbong1x** [comment]
> thx for the nice words :)

You're welcome, hope you take it to heart because its truly meant <3

**Comment by MrScautHD** [comment]
i do :) and I'm sharing it with Github support :)

**Comment by bingbong1x** [comment]
> excuse me sir, could you please keep beyond earth? i am sure that it is not too hard to say something like "remember to place your launchpad at least 200 blocks up to prevent some minor bugs". the beyond earth mod is a resurrection of my favorite mod and i have always been quite tied to space. please leave it in, i am sure if they know to make their pad a little higher they will not add anymore complaints

Sorry, it will definitely be removed. If you want to use it on your server, though I don't recommend it because its bug riddled, you can just throw it in your server. I will be adding another Rocketry mod officially though.

**Comment by bingbong1x** [comment]
> i do :) and I'm sharing it with Github support :)

Congratulations! I'm proud of you for actually doing something!

**Comment by MrScautHD** [comment]
> 

btw i hope it is ok if the users of your modpack know how you speak with others :)

**Comment by MrScautHD** [comment]
fun fakt im also a patner of bisect hosting :)

**Comment by bingbong1x** [comment]
I dont care? clearly? Calling me dumb because you're too blind to think about what you're saying isn't going to fly little one.

**Comment by MrScautHD** [comment]
:)

**Comment by bingbong1x** [comment]
(:

**Comment by MrScautHD** [comment]
bye bye 1 year old kid :)

**Comment by bingbong1x** [comment]
See ya
