### ISSUE TITLE
Suggestion: Add oil fluid to crude_oil fluid tag

### ISSUE THREAD

**Issue by JaisDK** [MrScautHD/Beyond-Earth#43]
Hello,

Could you add oil to the forge:crude_oil fluid tag to be compatible with other mods?

Like this: https://github.com/TeamPneumatic/pnc-repressurized/blob/1.16.5/src/generated/resources/data/forge/tags/fluids/crude_oil.json

**Comment by MrScautHD** [comment]
of course

**Comment by MrScautHD** [comment]
https://github.com/MrScautHD/Beyond-Earth/commit/f20c040cfb3a2c7b60c85dee8b4cb9931f9a7820
