### ISSUE TITLE
[1.18.1] Crash on Forge version .45 and above.

### ISSUE THREAD

**Issue by Gbergz** [MrScautHD/Beyond-Earth#46]
Title^

**Minecraft**: 1.18.1
**Forge**: 39.0.45
**Beyond Earth**: 6.0b

**Crash-Report**: https://gist.github.com/Gbergz/7939a5dbd4875767c125cf51e83db041

**-** Gbergz

**Comment by MrScautHD** [comment]
thx for your bug report i want to take a look on it

**Comment by GoldHeartTheOne** [comment]
I also got this bug.

Minecraft: 1.18.1
Forge: 39.0.55
Beyond Earth: 6.0b

Crash-Report: https://drive.google.com/file/d/1kVJOmmrvMhxmI7x1KJxPQcIts76Adzie/view?usp=sharing

**Comment by GoldHeartTheOne** [comment]
update: I had Beyond Earth disable and still got this crash with other mod block, I dont think it was BE that was causing this.

**Comment by MrScautHD** [comment]
> update: I had Beyond Earth disable and still got this crash with other mod block, I dont think it was BE that was causing this.

it is a BE problem but allot mods has this problem now because forge changed a thing that very often used for mods

**Comment by GoldHeartTheOne** [comment]
ah ok, so its forge fault ok.

**Comment by MrScautHD** [comment]
> ah ok, so its forge fault ok.

not really forge changed just code that my mod used before (so now is it not more compatible, and we need update to it)

**Comment by Klouver-github** [comment]
I also was bugged and to talk to the manager

**Comment by MrScautHD** [comment]
fixed https://github.com/MrScautHD/Beyond-Earth/commit/ba7cb0922e1c12aa0d12aa7a807c8a0b14691e2e

**Comment by Gbergz** [comment]
No stress, just wondering when this update is being published? Currently plagued by this crash a lot.

**Comment by Aulluna** [comment]
There is no ETA , but it is near dw

**Comment by Aulluna** [comment]
> I also was bugged and to talk to the manager

It smells like a karen in here

**Comment by Klouver-github** [comment]
excuse me I am not a KAren and let me talk to your manager too
