### ISSUE TITLE
Skybox rendering in front of distant objects.

### ISSUE THREAD

**Issue by Endrez42** [MrScautHD/Beyond-Earth#48]
The earth has a tendency to render in front of any object that is far away.

This is easily visible with a high render distance and a tower of max height on the moon.

Screenshot of it happening:

![2022-01-21_13 46 09](https://user-images.githubusercontent.com/78289126/150591100-faa46784-2aa4-44ba-8cb3-c1fa627b7d3f.png)

Tested without shaders or optifine. Still occurs.

**Comment by MrScautHD** [comment]
thx for your bug report!, i want to check it out

**Comment by MrScautHD** [comment]
Thx for your Bug Report is fixed in https://github.com/MrScautHD/Beyond-Earth/commit/6fad81c2f31838a9e863ec062696ec195adf7660
