### ISSUE TITLE
1.16 Crash on startup

### ISSUE THREAD

**Issue by Magi1053** [MrScautHD/Beyond-Earth#49]
```
Thread: Render thread
Stacktrace:
	at net.mrscauthd.boss_tools.ModInnet.<clinit>(ModInnet.java:468) ~[boss_tools:1.0] {re:classloading}
-- MOD boss_tools --
Details:
	Mod File: Space-BossTools-1.16.5-5.5e.jar
	Failure message: Space-BossTools (boss_tools) has failed to load correctly
		java.lang.NoSuchMethodError: net.minecraft.util.DamageSource.func_76348_h()Lnet/minecraft/util/DamageSource;
	Mod Version: 5.5e
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.NoSuchMethodError: net.minecraft.util.DamageSource.func_76348_h()Lnet/minecraft/util/DamageSource;
```
### Full Log: https://pastebin.com/raw/heTLR7vQ

**Comment by MrScautHD** [comment]
i think it is a to new forge verson or to old (we are supporting for normal this version not anymore)

**Comment by Aulluna** [comment]
He meant to say that the 1.16 version of the mod isnt supported anymore

**Comment by Magi1053** [comment]
I've tried multiple versions of forge with the same result, including the minimum version the mod requires. I get it you dont want to backport features to and older version but dont you think the mod crashing simply by installing it is a critical issue worth fixing??

**Comment by MrScautHD** [comment]
i do not get a crash

**Comment by Aulluna** [comment]
wait did u try reinstalling the mod itself ? ( also remove all related files )
