### ISSUE TITLE
[1.18.1] crash when using Nasa workbench or other machine.

### ISSUE THREAD

**Issue by BarbaDaBietola** [MrScautHD/Beyond-Earth#51]
evreytime i try to use a machine like Nasa workbench minecraft suddenly crushes, this happens with all version of BeyondEarth for mc 1.18.1
this is my crush log:
The game crashed whilst exception ticking world
Error: java.lang.NoSuchMethodError: 'net.minecraft.nbt.CompoundTag net.minecraft.world.level.block.entity.RandomizableContainerBlockEntity.save(net.minecraft.nbt.CompoundTag)'
Codice di uscita: -1

**Comment by MrScautHD** [comment]
yep we know already this bug is fixed with the next update

**Comment by BarbaDaBietola** [comment]
thanks a lot
