### ISSUE TITLE
Don't setfire to player on venus

### ISSUE THREAD

**Issue by gisellevonbingen** [MrScautHD/Beyond-Earth#54]
![Animation](https://user-images.githubusercontent.com/44163945/151395576-c2c705cb-ff51-4fb8-855a-a1368802ba8f.gif)

I think this line is causing
https://github.com/MrScautHD/Beyond-Earth/blob/1.18/src/main/java/net/mrscauthd/beyond_earth/events/Methods.java#L243

can't find 'entity instanceof Mob' statement in 1.16.5
that is added from [cd05fbdcfa6dbda08394e31515c735cd00af1ba4](https://github.com/MrScautHD/Beyond-Earth/commit/cd05fbdcfa6dbda08394e31515c735cd00af1ba4#diff-6abd41220e95a314519863475ccec5ac8126ddfb7fa8f9bc9290f4d23126d964)
is this intentional?

**Comment by MrScautHD** [comment]
thx :), is fixed with the next pull
