### ISSUE TITLE
Player don't damage from venus rain

### ISSUE THREAD

**Issue by gisellevonbingen** [MrScautHD/Beyond-Earth#56]
Player don't equip netherite space suit, but don't damage from venus rain

The condition in line number 257 seems to be behaving strangely?
https://github.com/MrScautHD/Beyond-Earth/blob/1.18/src/main/java/net/mrscauthd/beyond_earth/events/Methods.java#L254-L257

it changed from https://github.com/MrScautHD/Beyond-Earth/commit/f8ea8d89092ec9c20f29bb6d57a6ca723c9b1a91#diff-2c438d081419143bc88e9b318515d7c9bcba81db208b42d4b6a32240653ee1a1R275

**Comment by MrScautHD** [comment]
https://github.com/MrScautHD/Beyond-Earth/commit/bbce59219c63b74e76519fd4b17a8d3050ce8eda
