### ISSUE TITLE
Crash when interacting with Solar Panel

### ISSUE THREAD

**Issue by SatrWinner** [MrScautHD/Beyond-Earth#60]
When I placed down and interacted with the Solar Panel block, my game immediately crashed. Further attempts to load the world resulted in it crashing immediately again. I am using the current latest forge version. Note: In the comments under the CurseForge mod page, a couple of other people have reported the same issue with other machines from the mod.

Pastebin Link: https://pastebin.com/1pupZyzv

**Comment by MrScautHD** [comment]
Is already fixed
