### ISSUE TITLE
1.18.1-6.0d

### ISSUE THREAD

**Issue by BarbaDaBietola** [MrScautHD/Beyond-Earth#67]
when i try to reach a planet, a orbit or a space station it just bring me back to the overworld, it happens with every tier and every planet, (i tried in creative mod)

**Comment by BarbaDaBietola** [comment]
UPDATE
i tried in another world in survival and it seems to work

**Comment by BarbaDaBietola** [comment]
I found out that if you want to add the mod in an exsiting world when you try to reach every possible planet or orbit it just bring you back to the overworld . The problem does not occur if  you generate another world. I hope you fix this bug.

**Comment by MrScautHD** [comment]
Thats a Minecraft bug, sry i can not fix it
