### ISSUE TITLE
test spam in console

### ISSUE THREAD

**Issue by jeremiahwinsley** [MrScautHD/Beyond-Earth#68]
Looks like a debug line got left in here: https://github.com/MrScautHD/Beyond-Earth/blob/e9ee5d5b6e22abb6362783aba434f92ce947326d/src/main/java/net/mrscauthd/beyond_earth/machines/tile/OxygenBubbleDistributorBlockEntity.java#L122

**Comment by MrScautHD** [comment]
fixed, thx for you bug report :)
