### ISSUE TITLE
Beyond Earth mod crashes ATM7(All the mods 7) at startup when using OptiFine_1.18.1_HD_U_H4

### ISSUE THREAD

**Issue by jblankenship30** [MrScautHD/Beyond-Earth#70]
See attached crash report.

[crash-2022-02-04_17.40.32-client.txt](https://github.com/MrScautHD/Beyond-Earth/files/8006871/crash-2022-02-04_17.40.32-client.txt)

**Comment by MrScautHD** [comment]
1. You need to report it by ATM7
2. It is already fixed in my mod atm need just to update

**Comment by jblankenship30** [comment]
Thanks, I submitted an issue with ATM7 as well!
