### ISSUE TITLE
[1.16.5, v5.5e] Space Station Materials Are Not Tagged

### ISSUE THREAD

**Issue by Elfinlocks** [MrScautHD/Beyond-Earth#71]
Hello,

In the current version of Boss Tools/Beyond Earth for 1.16.5, version 5.5e, you cannot use iron plates and steel ingots from other mods for space station construction, it only accepts specifically the ones from space boss tools. Can this please be fixed? Space Stations are literally unusable in modpacks right now due to this. 

Thank you!

**Comment by MrScautHD** [comment]
1.16.5 not anymore supported

**Comment by Elfinlocks** [comment]
What if I made a pull request, would you push it?
