### ISSUE TITLE
Mod not working properly

### ISSUE THREAD

**Issue by LidorPrototype** [MrScautHD/Beyond-Earth#81]
No matter which start / station I'm trying to get to (tier 1-2-3-4) it will always make me land back on earth.
and when I'm choosing a space station, it will make me land on earth but the station will be on the ground there.

**Comment by MrScautHD** [comment]
its a minecraft bug make a new world

**Comment by LidorPrototype** [comment]
for some reason I have regular mobs spawning on the other planets (like cows and pigs)

**Comment by MrScautHD** [comment]
idk maybe a other mod
