### ISSUE TITLE
Unable to extract Fuel from Fuel Refinery using Pipez

### ISSUE THREAD

**Issue by ValkyrieofNight** [MrScautHD/Beyond-Earth#85]
Steps to replicate:

Place Refinery
Fill with Oil
Place pipe on any side and use pipe wrench to set to extract mode.
Place a tank next to the pipe.

It will output Oil instead of Fuel.

**Comment by MrScautHD** [comment]
1. If a bug like this exist is it Pipez that need to write that
2. just place the cable on the buttom side
