### ISSUE TITLE
Vanilla materials in Beyond Earth Ore Blocks and Items not tagged using `minecraft:x_ores` tag

### ISSUE THREAD

**Issue by Eelt** [MrScautHD/Beyond-Earth#93]
For compatibility with other mods--and vanilla--your ore blocks for vanilla resources especially should be tagged.
This would eliminate the need for unnecessary and redundant recipes, both from your mod and from other fellow modders, and even modpack developers/creators.

You'd ideally add a block and item tag for all Beyond Earth ores listed below:

# `minecraft:iron_ores`
The following should be tagged as `minecraft:iron_ores`:
* `beyond_earth:moon_iron_ore`
* `beyond_earth:mars_iron_ore`
* `beyond_earth:mercury_iron_ore`
* `beyond_earth:glacio_iron_ore`

# `minecraft:coal_ores`
The following should be tagged as `minecraft:coal_ores`:
* `beyond_earth:venus_coal_ore`
* `beyond_earth:glacio_coal_ore`

# `minecraft:gold_ores`
The following should be tagged as `minecraft:gold_ores`:
* `beyond_earth:venus_gold_ore`

# `minecraft:diamond_ores`
The following should be tagged as `minecraft:diamond_ores`:
* `beyond_earth:mars_diamond_ore`
* `beyond_earth:venus_diamond_ore`

# `minecraft:copper_ores`
The following should be tagged as `minecraft:copper_ores`:
* `beyond_earth:glacio_copper_ore`

# `minecraft:lapis_ores`
The following should be tagged as `minecraft:lapis_ores`:
* `beyond_earth:glacio_lapis_ore`

Since there is no difference in output between the Beyond Earth and Vanilla equivalent ores, I don't see why the ones added by Beyond Earth aren't rolled up in their respective Minecraft namespace tag. This would allow your blocks to be caught in recipes that use the tag `minecraft:x_ores` for their recipes, rather than manually have to make the recipes themselves, or tagging your blocks _for you_ in their mods.

**Comment by MrScautHD** [comment]
you are right! i want to do that laiter :D

**Comment by SDUBZ** [comment]
> you are right! i want to do that laiter :D

did you ever fix this because its a very basic thing you should already know
even only as a user i knew this many years ago

**Comment by gisellevonbingen** [comment]
Applied at #143

**Comment by MrScautHD** [comment]
Added
