### ISSUE TITLE
[1.18.2] Forge 40.0.18 breaks mod

### ISSUE THREAD

**Issue by Baggytrousers27** [MrScautHD/Beyond-Earth#99]
Beyond Earth (beyond_earth) has failed to load correctly
java.lang.reflect.InvocationTargetException: null

Beyond-Earth-1.18.2-6.0j
Forge 40.0.18

[Crashlog](https://pastebin.com/gNrjvjff)

**Comment by MrScautHD** [comment]
thx for you bug report, is fixed in the next version :D

**Comment by Baggytrousers27** [comment]
Marvellous.
ψ(｀∇´)ψ
